'use client'

import Link from 'next/link'

// ─── Data ─────────────────────────────────────────────────────────────────────

const METRICS = [
  { value: '80M+', label: 'Active gamers in Nigeria alone' },
  { value: '200M+', label: 'Players across 6 Sub-Saharan markets' },
  { value: '370M+', label: 'African diaspora addressable community' },
  { value: '45–60M', label: 'Social gaming segment — Nigeria, Ghana, Kenya, SA' },
]

const STREAMS = [
  {
    icon: '🎟',
    title: 'Event Organiser Licensing',
    tag: 'Primary B2B Revenue',
    description:
      'Event organisers pay for curated game packs designed for their event type and audience. Every organiser client brings hundreds of new players onto the platform at zero marginal acquisition cost.',
    tiers: [
      { label: 'Small (under 50 people)', value: '$50 flat fee per event' },
      { label: 'Medium (50–200 people)', value: '$2 per attendee' },
      { label: 'Large (200+ people)', value: '$1.50 per attendee' },
      { label: 'Enterprise annual licence', value: '$500–$2,000' },
    ],
  },
  {
    icon: '🔗',
    title: 'Wager Transaction Fees',
    tag: 'On-Chain Revenue',
    description:
      'Every wager placed through Conquest passes through the smart contract. Conquest takes 5% of every pot processed. The house also wins 100% of the pot when all wagering players guess incorrectly. Scales directly with player activity — no impact on gameplay fairness since wagers are always opt-in.',
    tiers: [],
  },
  {
    icon: '🏆',
    title: 'Esports & Tournament Commissions',
    tag: 'Competitive Revenue',
    description:
      'Conquest takes 10% of every prize pool processed through competitive tournaments. As tournament frequency and participation grows across markets, this becomes a significant and recurring revenue line.',
    tiers: [
      { label: 'Campus Cups entry fee', value: '$0.50 per player' },
      { label: 'City Leagues entry fee', value: '$1.00 per player' },
      { label: 'Conquest Championship', value: '$2.00 per player' },
    ],
  },
  {
    icon: '🛠',
    title: 'Creator Revenue Share',
    tag: 'Platform Revenue — Year 2',
    description:
      'Third-party game designers publish titles to the Conquest catalogue and earn 70% of revenue generated by their game. Conquest retains 30%. Expands the catalogue without Conquest bearing full development cost and creates a financial incentive for African game designers to build on the platform.',
    tiers: [],
  },
]

const COMMUNITY = [
  {
    icon: '💬',
    title: 'WhatsApp & Discord',
    body: 'WhatsApp is the primary community home for Nigerian and African players because that is where they already live. City-based groups for Enugu, Lagos, Port Harcourt, and Abuja run alongside a diaspora channel for UK and US players. Discord serves the competitive segment: tournament announcements, game feedback, and creator content. Two platforms, two audiences, one community.',
  },
  {
    icon: '🫂',
    title: 'Squads',
    body: 'Conquest does not use the word guilds. Recurring friend groups and gaming crews form Squads — a platform feature from Q2 2026 with shared identity, a squad leaderboard, and collective connection points. Squads mirror how people actually socialise: in tight circles, not open forums. They are the atomic unit of the Conquest community.',
  },
  {
    icon: '🎓',
    title: 'Ambassador Programme',
    body: 'Campus ambassadors are students who already host game nights or command social attention in their environment. Their job: run one Conquest session per month and grow their campus Squad. In return: early game access, a verified ambassador badge, and a small monthly AVAX reward once wager infrastructure is live. Launching on 3–5 campuses in Q2 2026, expanding to 10 by Q4 2026.',
  },
  {
    icon: '⚔️',
    title: 'Tournaments',
    body: 'Monthly Cabal tournaments with on-chain prize pools give the competitive segment a recurring reason to show up. Three tiers: Campus Cups, City Leagues, and the annual Conquest Championship with live event finals and a significant on-chain prize pool. Every tournament generates content, drives acquisition, and deepens player investment.',
  },
  {
    icon: '🗳',
    title: 'Community Input & Governance',
    body: 'Players vote on which Coming Soon title gets built next. Squads submit game mode suggestions. Tournament formats go to community vote each season. Lightweight governance built in from the start — no on-chain infrastructure required yet. A formal Conquest DAO is a Year 2 milestone when the community has the scale to make it meaningful.',
  },
  {
    icon: '📲',
    title: 'Creators',
    body: 'Five to ten creator partners treated as community members, not vendors: early access, direct product feedback channels, and platform featuring. Authentic session content from people who genuinely love the game builds trust that produced content never does.',
  },
]

const GTM_STAGES = [
  {
    range: '0 → 100',
    title: 'Inner Circle',
    body: '210 waitlist members from OyaMakeWeGroove and Gameverse, playtest participants, and the founder\'s direct network. These people need an invitation — and they are on.',
  },
  {
    range: '100 → 400',
    title: 'Live Events',
    body: 'Conquest returns to the event circuit in Enugu and Port Harcourt with the platform live. Attendees play, a QR code goes on screen, players join before they leave the room. Two to three events at proven conversion rates gets Conquest to 400 real players.',
  },
  {
    range: '400 → 700',
    title: 'Social Architect Programme',
    body: '20–30 hosts, community organisers, and WhatsApp group admins in Enugu, Lagos, and Port Harcourt get early access with one brief: host a Cabal session this week. Based on group sizes at previous Conquest events, each brings 8–15 players. The product is the incentive.',
  },
  {
    range: '700 → 1,000',
    title: 'Campus Seeding',
    body: 'One ambassador on 3–5 Southeast Nigerian campuses hosts a Cabal session. The room fills itself. This is a deliberate geographic beachhead. The model expands to Lagos, Abuja, and diaspora markets from Q3 2026.',
  },
]

const PHASES = [
  {
    phase: '01',
    label: 'Foundation',
    period: 'Now',
    status: 'live' as const,
    headline: 'Conquest — Cabal',
    items: [
      'Flagship game live: Cabal, a social deduction game set in Nigerian political life',
      'Bot mode for solo play and onboarding',
      'On-chain wagering via CabalWager on Avalanche Fuji',
      'Web3 wallet login — MetaMask, WalletConnect',
      'Real-time multiplayer via Supabase with up to 8 players',
      'Leaderboard, friend system, and player profiles',
    ],
  },
  {
    phase: '02',
    label: 'Events Layer',
    period: 'Q2 2026',
    status: 'building' as const,
    headline: 'Live Event Mode',
    items: [
      'Event organiser dashboard — host Conquest at any ticketed event',
      'Large-room mode supporting 20–100 simultaneous players',
      'QR-code session join for walk-in audiences',
      'Branded event packs: custom characters, room themes, prize pools',
      'Squads launch — shared identity for recurring friend groups',
      'Ambassador programme on 3–5 campuses in Southeast Nigeria',
    ],
  },
  {
    phase: '03',
    label: 'Catalogue Expansion',
    period: 'Q3–Q4 2026',
    status: 'planned' as const,
    headline: 'The Second Game',
    items: [
      'Second title launches — from the "Coming Soon" catalogue, chosen by community vote',
      'Shared wallet and profile system across all Conquest games',
      'Achievement system with on-chain badge ownership',
      'Expansion into Ghana, Kenya, and South Africa',
      'African diaspora marketing push (UK, US, Canada)',
      'Platform reaches 150,000 monthly active users',
    ],
  },
  {
    phase: '04',
    label: 'Platform Scale',
    period: '2027',
    status: 'planned' as const,
    headline: 'The Long Game',
    items: [
      '500,000–1M monthly active users across five markets',
      'Full game catalogue: Ludo Splash, Ọwọ Ni Kọkọ, Ayò, and more',
      'Creator tools: build and publish your own Conquest game mode',
      'Conquest DAO — on-chain community governance at scale',
      'Annual Conquest Championship with live event finals and on-chain prize pool',
      'Conquest becomes the defining social platform for the African generation',
    ],
  },
]

// ─── Status badge ─────────────────────────────────────────────────────────────
function StatusBadge({ status }: { status: 'live' | 'building' | 'planned' }) {
  const map = {
    live:     { label: 'Live',     bg: '#1E4035', text: '#6EE7B7' },
    building: { label: 'Building', bg: '#3B2506', text: '#C9A84C' },
    planned:  { label: 'Planned',  bg: '#1C1710', text: '#C4B090' },
  }
  const { label, bg, text } = map[status]
  return (
    <span className="text-xs font-mono tracking-widest uppercase px-2 py-0.5 rounded-full" style={{ background: bg, color: text }}>
      {label}
    </span>
  )
}

// ─── Page ─────────────────────────────────────────────────────────────────────
export default function VisionPage() {
  return (
    <div className="min-h-screen" style={{ background: 'var(--parchment)' }}>

      {/* ── Nav ── */}
      <nav
        className="sticky top-0 z-30 flex items-center justify-between px-6 py-4 border-b"
        style={{ background: 'rgba(245,237,218,0.92)', backdropFilter: 'blur(12px)', borderColor: 'var(--parchment-deep)' }}
      >
        <Link href="/" className="flex items-center gap-2">
          <img src="/Conquest_Logo.jpg" alt="Conquest" className="h-9 w-auto" />
          <span className="font-display font-black text-xl tracking-tight" style={{ color: 'var(--ink)', fontFamily: 'Fraunces, serif' }}>
            Conquest
          </span>
        </Link>
        <div className="flex items-center gap-6">
          <Link href="/" className="text-sm font-medium" style={{ color: 'var(--ink-soft)' }}>Play</Link>
          <Link href="/leaderboard" className="text-sm font-medium" style={{ color: 'var(--ink-soft)' }}>Leaderboard</Link>
          <Link href="/vision" className="text-sm font-semibold" style={{ color: 'var(--terracotta)' }}>Vision</Link>
        </div>
      </nav>

      {/* ── Hero ── */}
      <section className="relative overflow-hidden px-6 pt-24 pb-20 text-center">
        <div
          className="absolute inset-0 pointer-events-none"
          style={{ background: 'radial-gradient(ellipse at 50% 0%, rgba(201,168,76,0.12) 0%, transparent 65%)' }}
        />
        <div className="relative max-w-3xl mx-auto">
          <p className="text-xs font-mono tracking-[0.3em] uppercase mb-6" style={{ color: 'var(--gold)' }}>
            Product Vision
          </p>
          <h1
            className="text-5xl sm:text-6xl font-black leading-[1.05] mb-8"
            style={{ fontFamily: 'Fraunces, serif', color: 'var(--ink)' }}
          >
            Human connection<br />
            <span style={{ color: 'var(--terracotta)' }}>deserves infrastructure.</span>
          </h1>
          <p className="text-lg leading-relaxed max-w-2xl mx-auto" style={{ color: 'var(--ink-soft)' }}>
            The tools people use to stay close — messaging apps, video calls, social media — are passive.
            They let you observe each other. Conquest is building the <em>active layer</em>: a platform
            where people do things together, and those shared experiences compound into something real over time.
          </p>
        </div>
      </section>

      {/* ── Vision body ── */}
      <section className="px-6 pb-24">
        <div className="max-w-3xl mx-auto space-y-10">
          <blockquote className="border-l-4 pl-6 py-2" style={{ borderColor: 'var(--gold)', fontFamily: 'Fraunces, serif' }}>
            <p className="text-2xl font-semibold leading-snug" style={{ color: 'var(--ink)' }}>
              &ldquo;Every game played is a deposit into a relationship. Every laugh, every accusation
              across the table, every late-night session with someone three time zones away —
              Conquest captures that and gives it meaning.&rdquo;
            </p>
          </blockquote>
          <div className="space-y-6 text-base leading-relaxed" style={{ color: 'var(--ink-soft)' }}>
            <p>
              The long-term vision is a platform that serves every context where people want to connect:
              intimate friend groups, large live events, long-distance relationships, online communities,
              and competitive esports leagues — with a growing catalogue of games designed specifically
              to create those moments. Not games for gaming&rsquo;s sake. Games engineered for human connection.
            </p>
            <p>
              Conquest is building from Africa outward. The platform is rooted in Nigerian and West African
              identity: the characters, the language, the humour, the social dynamics. That specificity is
              the foundation for global relevance. The product does not borrow from a universal template
              and apply a cultural veneer. The culture is the architecture.
            </p>
            <p>
              On-chain infrastructure powers the trust and rewards layer: wagers, prize pools, achievement
              ownership. But it is never the product. The product is the feeling of being in a room —
              physical or digital — fully present with the people you care about, doing something that makes
              you lose track of time.
            </p>
            <p className="font-semibold" style={{ color: 'var(--ink)' }}>
              That is the future Conquest is building toward. Not a gaming app. A new social ritual —
              and a very successful business.
            </p>
          </div>
        </div>
      </section>

      {/* ── Market ── */}
      <section className="px-6 py-20" style={{ background: 'var(--parchment-deep)' }}>
        <div className="max-w-5xl mx-auto">
          <p className="text-xs font-mono tracking-[0.3em] uppercase mb-3 text-center" style={{ color: 'var(--gold)' }}>
            The Opportunity
          </p>
          <h2 className="text-3xl sm:text-4xl font-black text-center mb-14" style={{ fontFamily: 'Fraunces, serif', color: 'var(--ink)' }}>
            370 million people.<br />Zero platforms built for them.
          </h2>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-6">
            {METRICS.map(m => (
              <div key={m.label} className="rounded-2xl p-6 flex flex-col gap-2" style={{ background: 'var(--parchment)', border: '1px solid rgba(201,168,76,0.25)' }}>
                <span className="text-4xl font-black" style={{ fontFamily: 'Fraunces, serif', color: 'var(--terracotta)' }}>{m.value}</span>
                <span className="text-sm leading-snug" style={{ color: 'var(--ink-soft)' }}>{m.label}</span>
              </div>
            ))}
          </div>
          <p className="text-sm text-center mt-8 max-w-2xl mx-auto" style={{ color: 'var(--ink-soft)' }}>
            Nigeria alone has over 80 million active gamers — the majority aged 18–35, mobile-first, socially
            connected, and deeply underserved by platforms not built with them in mind. Conquest&rsquo;s immediate
            serviceable market in Nigeria, Ghana, Kenya, and South Africa represents 45–60 million active social players.
          </p>
        </div>
      </section>

      {/* ── Business Model ── */}
      <section className="px-6 py-20">
        <div className="max-w-5xl mx-auto">
          <p className="text-xs font-mono tracking-[0.3em] uppercase mb-3 text-center" style={{ color: 'var(--gold)' }}>
            Business Model
          </p>
          <h2 className="text-3xl sm:text-4xl font-black text-center mb-4" style={{ fontFamily: 'Fraunces, serif', color: 'var(--ink)' }}>
            Free for players.<br />Sustainable through the ecosystem.
          </h2>
          <p className="text-base text-center max-w-2xl mx-auto mb-14" style={{ color: 'var(--ink-soft)' }}>
            The consumer product is free forever. Revenue comes from the businesses and transactions that
            the player base enables. The players are not the revenue — they are the infrastructure that makes revenue possible.
          </p>

          <div className="space-y-6">
            {STREAMS.map(s => (
              <div key={s.title} className="rounded-2xl p-7" style={{ background: 'var(--parchment-deep)', border: '1px solid rgba(201,168,76,0.2)' }}>
                <div className="flex flex-wrap items-start justify-between gap-4 mb-4">
                  <div className="flex items-center gap-3">
                    <span className="text-2xl">{s.icon}</span>
                    <div>
                      <h3 className="text-lg font-bold" style={{ color: 'var(--ink)' }}>{s.title}</h3>
                      <span className="text-xs font-mono tracking-widest uppercase" style={{ color: 'var(--gold)' }}>{s.tag}</span>
                    </div>
                  </div>
                </div>
                <p className="text-sm leading-relaxed mb-4" style={{ color: 'var(--ink-soft)' }}>{s.description}</p>
                {s.tiers.length > 0 && (
                  <div className="rounded-xl overflow-hidden" style={{ border: '1px solid rgba(201,168,76,0.15)' }}>
                    {s.tiers.map((t, i) => (
                      <div
                        key={i}
                        className="flex items-center justify-between px-4 py-3 text-sm"
                        style={{
                          background: i % 2 === 0 ? 'rgba(201,168,76,0.05)' : 'transparent',
                          borderTop: i > 0 ? '1px solid rgba(201,168,76,0.1)' : 'none',
                        }}
                      >
                        <span style={{ color: 'var(--ink-soft)' }}>{t.label}</span>
                        <span className="font-semibold font-mono" style={{ color: 'var(--ink)' }}>{t.value}</span>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            ))}
          </div>

          {/* Revenue at scale */}
          <div className="mt-10 grid sm:grid-cols-2 gap-6">
            <div className="rounded-2xl p-8" style={{ background: 'var(--ink)', border: '1px solid rgba(201,168,76,0.3)' }}>
              <p className="text-xs font-mono tracking-widest uppercase mb-2" style={{ color: 'var(--gold)' }}>Early Stage</p>
              <p className="text-3xl font-black mb-2" style={{ fontFamily: 'Fraunces, serif', color: 'var(--parchment)' }}>$8K–$15K<span className="text-lg font-normal"> /mo</span></p>
              <p className="text-sm leading-relaxed" style={{ color: 'var(--ink-faint)' }}>
                At 25,000 MAU with 20 event organiser clients and modest wager activity.
              </p>
            </div>
            <div className="rounded-2xl p-8" style={{ background: 'var(--ink)', border: '1px solid rgba(201,168,76,0.3)' }}>
              <p className="text-xs font-mono tracking-widest uppercase mb-2" style={{ color: 'var(--gold)' }}>Growth Stage</p>
              <p className="text-3xl font-black mb-2" style={{ fontFamily: 'Fraunces, serif', color: 'var(--parchment)' }}>$80K–$120K<span className="text-lg font-normal"> /mo</span></p>
              <p className="text-sm leading-relaxed" style={{ color: 'var(--ink-faint)' }}>
                At 150,000 MAU across four markets with active tournament infrastructure.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* ── Community ── */}
      <section className="px-6 py-20" style={{ background: 'var(--parchment-deep)' }}>
        <div className="max-w-5xl mx-auto">
          <p className="text-xs font-mono tracking-[0.3em] uppercase mb-3 text-center" style={{ color: 'var(--gold)' }}>
            Community
          </p>
          <h2 className="text-3xl sm:text-4xl font-black text-center mb-4" style={{ fontFamily: 'Fraunces, serif', color: 'var(--ink)' }}>
            Every session is already<br />a community event.
          </h2>
          <p className="text-base text-center max-w-xl mx-auto mb-14" style={{ color: 'var(--ink-soft)' }}>
            The strategy is to capture, organise, and reward what is already happening.
          </p>
          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5">
            {COMMUNITY.map(c => (
              <div key={c.title} className="rounded-2xl p-6 flex flex-col gap-3" style={{ background: 'var(--parchment)', border: '1px solid rgba(201,168,76,0.2)' }}>
                <span className="text-2xl">{c.icon}</span>
                <h3 className="text-base font-bold" style={{ color: 'var(--ink)' }}>{c.title}</h3>
                <p className="text-sm leading-relaxed" style={{ color: 'var(--ink-soft)' }}>{c.body}</p>
              </div>
            ))}
          </div>
          <p className="text-sm text-center mt-10 max-w-2xl mx-auto font-medium" style={{ color: 'var(--ink-soft)' }}>
            By Year 2, the Conquest community is a network of Squads across five African markets and three
            diaspora cities — connected by shared cultural identity, a growing catalogue, and a competitive
            season everyone has something to play for.
          </p>
        </div>
      </section>

      {/* ── First 1,000 players ── */}
      <section className="px-6 py-20">
        <div className="max-w-4xl mx-auto">
          <p className="text-xs font-mono tracking-[0.3em] uppercase mb-3 text-center" style={{ color: 'var(--gold)' }}>
            Go-to-Market
          </p>
          <h2 className="text-3xl sm:text-4xl font-black text-center mb-4" style={{ fontFamily: 'Fraunces, serif', color: 'var(--ink)' }}>
            The first 1,000 players<br />come from rooms.
          </h2>
          <p className="text-base text-center max-w-2xl mx-auto mb-4" style={{ color: 'var(--ink-soft)' }}>
            This is not a theory. At OyaMakeWeGroove in Lagos, 60 people played and joined the waitlist.
            At Gameverse in Port Harcourt, over 150 did the same. Before the digital product launched,
            Conquest had 210 people actively waiting for it.
          </p>
          <p className="text-base text-center max-w-xl mx-auto mb-14 font-medium" style={{ color: 'var(--ink)' }}>
            The path to 1,000 is a continuation of something already in motion.
          </p>

          {/* Stages */}
          <div className="space-y-4 mb-14">
            {GTM_STAGES.map((s, i) => (
              <div key={s.range} className="flex gap-6 items-start rounded-2xl p-6" style={{ background: 'var(--parchment-deep)', border: '1px solid rgba(201,168,76,0.2)' }}>
                <div className="flex-shrink-0 text-center" style={{ minWidth: 72 }}>
                  <div
                    className="text-xs font-mono font-bold rounded-full px-3 py-1 inline-block"
                    style={{ background: i === 0 ? 'var(--gold)' : 'rgba(201,168,76,0.12)', color: i === 0 ? 'var(--ink)' : 'var(--gold)' }}
                  >
                    {s.range}
                  </div>
                </div>
                <div>
                  <h3 className="font-bold mb-1" style={{ color: 'var(--ink)' }}>{s.title}</h3>
                  <p className="text-sm leading-relaxed" style={{ color: 'var(--ink-soft)' }}>{s.body}</p>
                </div>
              </div>
            ))}
          </div>

          {/* Additional channels */}
          <div className="grid sm:grid-cols-2 gap-5 mb-10">
            <div className="rounded-2xl p-6" style={{ background: 'var(--parchment-deep)', border: '1px solid rgba(201,168,76,0.2)' }}>
              <h3 className="font-bold mb-2" style={{ color: 'var(--ink)' }}>Content & Creators</h3>
              <p className="text-sm leading-relaxed" style={{ color: 'var(--ink-soft)' }}>
                2–3 lifestyle creators in the 10K–50K follower range post genuine session footage. Brief: host a session with your friends and post what happens. Early creators get platform featuring and first access to Full Mode.
              </p>
            </div>
            <div className="rounded-2xl p-6" style={{ background: 'var(--parchment-deep)', border: '1px solid rgba(201,168,76,0.2)' }}>
              <h3 className="font-bold mb-2" style={{ color: 'var(--ink)' }}>Referral & Virality</h3>
              <p className="text-sm leading-relaxed" style={{ color: 'var(--ink-soft)' }}>
                The friend ID system is a built-in referral loop. Shareable win/loss cards at game end are designed to be posted and create curiosity. A small on-chain tournament with a modest AVAX prize pool generates competitive word of mouth that content alone cannot.
              </p>
            </div>
          </div>

          {/* 1,000 player profile */}
          <div className="rounded-2xl p-8" style={{ background: 'var(--ink)', border: '1px solid rgba(201,168,76,0.3)' }}>
            <p className="text-xs font-mono tracking-widest uppercase mb-4" style={{ color: 'var(--gold)' }}>The 1,000 Player Profile</p>
            <p className="text-sm mb-6" style={{ color: 'var(--ink-faint)' }}>
              Not sign-ups. People who have played a complete game and felt what Conquest is.
            </p>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
              {[
                { pct: '40%', label: 'Live events' },
                { pct: '30%', label: 'Social Architect & campus seeding' },
                { pct: '20%', label: 'Organic social' },
                { pct: '10%', label: 'Friend ID referrals' },
              ].map(d => (
                <div key={d.label} className="text-center">
                  <p className="text-3xl font-black mb-1" style={{ fontFamily: 'Fraunces, serif', color: 'var(--gold)' }}>{d.pct}</p>
                  <p className="text-xs leading-snug" style={{ color: 'var(--ink-faint)' }}>{d.label}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* ── Roadmap ── */}
      <section className="px-6 py-20" style={{ background: 'var(--ink)' }}>
        <div className="max-w-4xl mx-auto">
          <p className="text-xs font-mono tracking-[0.3em] uppercase mb-3 text-center" style={{ color: 'var(--gold)' }}>
            Roadmap
          </p>
          <h2 className="text-3xl sm:text-4xl font-black text-center mb-16" style={{ fontFamily: 'Fraunces, serif', color: 'var(--parchment)' }}>
            Where we are.<br />Where we&rsquo;re going.
          </h2>
          <div className="relative">
            <div className="absolute left-[27px] top-6 bottom-6 w-px" style={{ background: 'rgba(201,168,76,0.2)' }} />
            <div className="space-y-10">
              {PHASES.map((p) => (
                <div key={p.phase} className="relative flex gap-8">
                  <div className="relative flex-shrink-0 flex flex-col items-center" style={{ width: 56 }}>
                    <div
                      className="w-14 h-14 rounded-full flex items-center justify-center text-lg font-black z-10"
                      style={{
                        fontFamily: 'Fraunces, serif',
                        background: p.status === 'live' ? 'var(--gold)' : p.status === 'building' ? '#3B2506' : '#1C1710',
                        color: p.status === 'live' ? 'var(--ink)' : 'var(--parchment)',
                        border: p.status === 'live' ? 'none' : '1px solid rgba(201,168,76,0.25)',
                      }}
                    >
                      {p.phase}
                    </div>
                  </div>
                  <div
                    className="flex-1 rounded-2xl p-7 mb-1"
                    style={{
                      background: p.status === 'live' ? 'rgba(201,168,76,0.08)' : 'rgba(255,255,255,0.03)',
                      border: p.status === 'live' ? '1px solid rgba(201,168,76,0.3)' : '1px solid rgba(255,255,255,0.07)',
                    }}
                  >
                    <div className="flex flex-wrap items-center gap-3 mb-1">
                      <span className="text-xs font-mono tracking-widest uppercase" style={{ color: 'var(--gold)' }}>{p.label}</span>
                      <StatusBadge status={p.status} />
                      <span className="text-xs font-mono" style={{ color: 'var(--ink-faint)' }}>{p.period}</span>
                    </div>
                    <h3 className="text-xl font-black mb-4" style={{ fontFamily: 'Fraunces, serif', color: 'var(--parchment)' }}>
                      {p.headline}
                    </h3>
                    <ul className="space-y-2">
                      {p.items.map((item, i) => (
                        <li key={i} className="flex items-start gap-3 text-sm" style={{ color: 'var(--ink-faint)' }}>
                          <span className="mt-[3px] flex-shrink-0" style={{ color: 'var(--gold)' }}>—</span>
                          {item}
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* ── Closing ── */}
      <section className="px-6 py-24 text-center">
        <div className="max-w-2xl mx-auto">
          <img src="/Conquest_Logo.jpg" alt="Conquest" className="h-16 w-auto mx-auto mb-8 opacity-80" />
          <h2 className="text-3xl sm:text-4xl font-black mb-6" style={{ fontFamily: 'Fraunces, serif', color: 'var(--ink)' }}>
            Not a gaming app.<br />A new social ritual.
          </h2>
          <p className="text-base mb-10 leading-relaxed" style={{ color: 'var(--ink-soft)' }}>
            Conquest is building from Africa outward — rooted in Nigerian and West African identity,
            engineered for global relevance. Join us at the table.
          </p>
          <Link
            href="/"
            className="inline-block px-8 py-4 rounded-full text-sm font-bold tracking-wide transition-opacity hover:opacity-80"
            style={{ background: 'var(--terracotta)', color: '#fff' }}
          >
            Play Conquest
          </Link>
        </div>
      </section>

      {/* ── Footer ── */}
      <footer className="px-6 py-8 flex items-center justify-between border-t" style={{ borderColor: 'var(--parchment-deep)', color: 'var(--ink-soft)' }}>
        <div className="flex items-center gap-2">
          <img src="/Conquest_Logo.jpg" alt="Conquest" className="h-7 w-auto opacity-70" />
          <span className="font-display font-black text-sm" style={{ fontFamily: 'Fraunces, serif' }}>Conquest</span>
          <span className="text-sm ml-1">by Yelobyte Studios</span>
        </div>
        <div className="flex gap-6 text-sm">
          <Link href="/" className="hover:opacity-70">Play</Link>
          <Link href="/leaderboard" className="hover:opacity-70">Leaderboard</Link>
          <Link href="/friends" className="hover:opacity-70">Friends</Link>
        </div>
      </footer>

    </div>
  )
}
